# Generated by Django 5.2.8 on 2025-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0002_subscription_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='services',
            field=models.CharField(default='', max_length=50),
        ),
    ]
